# Source - https://stackoverflow.com/a/69849731
# Posted by vre, modified by community. See post 'Timeline' for change history
# Retrieved 2026-04-22, License - CC BY-SA 4.0

name: Compilar al hacer push
on: [push]
jobs:
  compilar-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Instalar paquete xorg-dev"
        run: apt -y install xorg-dev
      - name: "Crear directorio build y ejecutar CMake"
        run: cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release
      - name: "Compilar proyecto" 
        run: cmake --build build --target all --config Release -- -j4
