name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: List contents of current directory
      run: ls
    - name: Clone repository
      run: git clone https://github.com/MascaChapas27/Erase-un-combate
    - name: Change directory to the repository directory
      run: cd Erase-un-combate
    - name: List contents of repository
      run: ls
    - name: Create build directory
      run: mkdir build
    - name: Change directory to build directory
      run: cd build
    - name: Create ninja.build using CMake
      run: cmake .. -G Ninja
    - name: Compile using ninja
      run: ninja
